### ISSUE TITLE
Request for listing this project to our document and becoming a maintainer

### ISSUE THREAD

**Issue by bonty** [koshilife/timetree-api-ruby-client#28]
Hello! I'm a developer of TimeTree. Thank you for creating our API client.

We are planning to add an SDK list in various languages to [our API document](https://developers.timetreeapp.com/ja/docs/api/overview). Are you okay to add this project to the SDK list?

And if you are okay, we would like to become the maintainer of this project(also [omniauth-timetree](https://github.com/koshilife/omniauth-timetree)).

Thanks.

**Comment by koshilife** [comment]
Hi @bonty,

>Are you okay to add this project to the SDK list?

Yes, It's my pleasure.

>And if you are okay, we would like to become the maintainer of this project(also omniauth-timetree).

Your proposal that the people inside TimeTree company will join as collaborators is great, so I almost agree.

Could you share your ideas what you want to contribute to these libraries as collaborators/maintainers?

**Comment by bonty** [comment]
Thanks for the reply and agreement!

Last month we released a different type of authentication than OAuth, called [CalenarApp](https://developers.timetreeapp.com/docs/api/calendar-app), so I'd like to add an implementation for it, and I'm implementing it now.
CalenarApp is an application that allows you to act like a participant in a calendar in a nutshell(similar to the [GitHub Apps](https://docs.github.com/en/free-pro-team@latest/developers/apps/about-apps#about-github-apps)).

I'm also considering the following other things

- Use a deserializer library because the response is in JSON:API format
- Add the validation of each attribute to the model class
- Sample Server Implementation

What do you think?

**Comment by koshilife** [comment]
@bonty Thank you for your reply.
I didn't know about Calendar App.
I would appreciate it if you could contribute that. I am reassured. 

I invited you into this project and omniauth-timetree project as a collaborator.
Could you check the invitations?

As you create a first pull request, let me check.
if you get stuck something, please feel free to contact me.

**Comment by bonty** [comment]
@koshilife Thank you for inviting me to this project!
I'll be creating a pull request as soon as possible.

**Comment by koshilife** [comment]
OK, thanks, @bonty.
